version: '3.8'
services:
  azguards-application:
    image: azguards-application:latest
    build: .
    container_name: 'azguards-application'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://13.235.12.7:3306/azguards_application?allowMultiQueries=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - '8090:8090'
    networks:
      - azguards-whatsapp
    depends_on:
      kafka:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8090/actuator/health"]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 3s

  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: azguards_application
      MYSQL_USER: azguards_application
      MYSQL_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - azguards-whatsapp

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - azguards-whatsapp
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - azguards-whatsapp
    volumes:
      - kafkadata:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8081:8080
    environment:
      SERVER_PORT: 8080
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_BROKER: kafka:9092
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - azguards-whatsapp

networks:
  azguards-whatsapp:
    driver: bridge

volumes:
  dbdata:
  kafkadata: